# Generated by Django 5.0.8 on 2024-08-07 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeExplainer',
            new_name='QueryExplainer',
        ),
    ]
