# Generated by Django 5.0.8 on 2024-08-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_codeexplainer_queryexplainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_input', models.TextField()),
                ('_output', models.TextField()),
            ],
            options={
                'db_table': 't_code_add_document',
            },
        ),
    ]
