# Generated by Django 5.0.8 on 2024-08-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adddocumentmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adddocumentmodel',
            table='t_add_document',
        ),
        migrations.AlterModelTable(
            name='queryexplainer',
            table='t_query',
        ),
    ]
