# Generated by Django 5.0.8 on 2024-08-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_adddocumentmodel_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscribeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.TextField()),
                ('session_id', models.TextField()),
                ('description', models.TextField()),
                ('user', models.TextField()),
                ('date', models.TextField()),
                ('_output', models.TextField()),
            ],
            options={
                'db_table': 't_transcribe',
            },
        ),
    ]
