# Generated by Django 5.0.8 on 2024-09-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_codeexplainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcribemodel',
            old_name='user',
            new_name='client',
        ),
    ]
